= Положение о защите персональных данных
:toc:
:toc-title: Содержание

:sectlink:



:numbered:
== Термины, определения и используемые сокращения

В настоящем Положении используются следующие термины и определения:

Персональные данные:: 
	любая информация, относящаяся к прямо или косвенно определенному или определяемому физическому лицу (субъекту персональных данных).
Обработка персональных данных:: 
	любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.
Оператор персональных данных::
	государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.
Распространение персональных данных::
	действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц.
Блокирование персональных данных::
	временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных).
Уничтожение персональных данных::
	действия, в результате которых становится невозможным восстановить содержание персональных данных в информационной системе персональных данных и (или) в результате которых уничтожаются материальные носители персональных данных.
Обезличивание персональных данных:: 
	действия, в результате которых становится невозможным без использования дополнительной информации определить принадлежность персональных данных конкретному субъекту персональных данных.
Информационная система персональных данных (ИСПДн)- совокупность содержащихся в базах данных персональных данных и обеспечивающих их обработку информационных технологий и технических средств.
Конфиденциальность персональных данных::
	обязательное для соблюдения оператором или иным получившим доступ к персональным данным лицом требование не допускать их распространения или предоставления третьим лицам без согласия субъекта персональных данных или требования Федерального закона.
Трансграничная передача персональных данных::
	передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому лицу или иностранному юридическому лицу.
Персональные данные, сделанные общедоступными субъектом персональных данных::
	персональные данные, доступ неограниченного круга лиц к которым предоставлен с согласия субъекта персональных данных либо по его просьбе.
Контролируемая зона::
	пространство (территория, здание, часть здания, помещение), в котором исключено неконтролируемое пребывание лиц, не имеющих постоянного или разового допуска, и посторонних транспортных средств.
Несанкционированный доступ (несанкционированные действия)::
	доступ к информации или действия с информацией, осуществляемые с нарушением установленных прав и (или) правил доступа к информации или действий с ней с применением штатных средств информационной системы или средств, аналогичных им по функциональным и техническим характеристикам.
Работодатель::
	ЗАО КБ «ЛАДА-КРЕДИТ», вступивший в трудовые отношения с Работником и правовые отношения с соискателем на вакантную должность.
Работник::
	физическое лицо, вступившее в трудовые отношения с ЗАО КБ «ЛАДА-КРЕДИТ».
Соискатель::
	физическое лицо, вступившее в правовые отношения с ЗАО КБ «ЛАДА-КРЕДИТ» с целью устройства на работу в ЗАО КБ «ЛАДА-КРЕДИТ».

	


== Назначение и область действия документа

Положение об обеспечении безопасности персональных данных (далее -Положение) предназначено для организации работ по защите персональных данных от неправомерного или случайного доступа к ним, уничтожения, изменения, блокирования, копирования, предоставления, распространения персональных данных, а также от иных неправомерных действий в отношении персональных данных при их обработке в <Наименование организации> (далее - Организация)

Требования настоящего Положения распространяются на структурные подразделения Организации и должностных лиц, принимающих участие в обеспечении безопасности ПДн, в т. ч. на Комиссию по обеспечению безопасности персональных данных (далее – Комиссия).

Настоящее Положения не распространяется на обеспечение безопасности сведений ограниченного доступа (в т. ч. конфиденциальной информации), не содержащих ПДн.

Требования настоящего Положения должны быть доведены до всех лиц, участвующих в обеспечении безопасности ПДн в Организации, под подпись.

== Мероприятия в рамках обеспечения безопасности ПДн

Настоящее Положение разработано в соответствии с Конституцией РФ, Трудовым кодексом РФ, Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных», Федеральным законом от 27.07.2006 № 149-ФЗ «Об информатизации, информационных технологиях и о защите информации», Постановлениями Правительства РФ от 01.11.2012 № 1119 «Об утверждении требований к защите персональных данных при их обработке в информационных системах персональных данных» и от 15.09.2008 № 687 «Об утверждении Положения об особенностях обработки персональных данных, осуществляемой без использования средств автоматизации», Распоряжением Правительства РФ от 21.03.1994 № 358-р «Об обеспечении сохранности документов по личному составу» и иными нормативными актами, действующими на территории Российской Федерации
	
Мероприятия в рамках обеспечения безопасности ПДн осуществляются в рамках проведения следующих работ:
	
	* Определение правил доступа к персональным данным;
	* Контроль физического доступа к компонентам информационных систем персональных данных;
	* Организация работы с носителями ПДн;
	* Определение порядка резервирования персональных данных;
	* Обнаружение фактов несанкционированного доступа к персональным данным и принятием мер;
	* Контроль за обеспечением необходимого уровня защищенности ПДн;
	* Построение системы защиты ПДн.

=== Правила доступа к персональным данным

==== Предоставление прав доступа

Работники ЗАО КБ «ЛАДА-КРЕДИТ» выполняют действия по обработке персональных данных в соответствии со служебной необходимостью и возложенными на Работников функциями.

Доступ к персональным данным предоставляется в соответствии с документом "Список лиц, допущенных к обработке персональных данных" (далее - Список). Список разрабатывается работником, ответственным за организацию обработки ПДн, согласуется с работником, ответственным за обеспечение безопасности ПДн и утверждается Председателем правления ЗАО КБ "ЛАДА-КРЕДИТ".

Основанием для предоставления прав доступа к ПДн являются:

- прием нового работника в штат ЗАО КБ "ЛАДА-КРЕДИТ" на должность, подразумевающую обработку ПДн работником для выполнения своих служебных обязанностей;
- перевод работника на должность, подразумевающую обработку ПДн работником.

Для предоставления доступа, руководитель структурного подразделения, к которому относится работник, направляет работнику, ответсвенному за обеспечение безопасности ПДн заявку на предоставление доступа в соответствии с разделом <<Оформление заявок на доступ к ПДн>> 

По завершении предоставления доступа работнику, ответственный за безопасность ПДн уведомляет об этом руководителя, оформившего Заявку, электронным письмом или по телефону (срок исполнения Заявки не превышает *3* рабочих дней).

==== Изменение или прекращение прав доступа

Основанием для пересмотра или прекращения прав доступа являются:
- увольнение работинка;
- перевод работника на другую должность, если новая должность подразумевает изменение или прекращение прав доступа к ПДн;
- проведение в отношении работника служебного расследования, если в рамках расследования работнику ограничивается доступ к ПДн.

Для изменения или прекращениея прав доступа, руководитель структурного подразделения, к которому относится работник, направляет работнику, ответсвенному за обеспечение безопасности ПДн заявку в соответствии с разделом <<Оформление заявок на доступ к ПДн>> 

По завершении предоставления доступа работнику, ответственный за безопасность ПДн уведомляет об этом руководителя, оформившего Заявку, электронным письмом или по телефону (срок исполнения Заявки не превышает *3* рабочих дней).


==== Оформление заявок на доступ к ПДн

В данном разделе изложен порадок оформления заявок на предоставление, изменение или прекращение прав доступа к ПДн (далее – Заявка) 
Оформление Заявки осуществляется одним из следующих способов:

- заявка в бумажном виде;
- электронная заявка.

Заявка подается ответственному за обеспечение безопасности ПДн от имени Руководителя структурного подразделения, в котором числится работник. Заявка содержит следующие сведения:

- Ф.И.О. и должность руководителя структурного подразделения, подающего Заявку;
- Ф.И.О. и должность работника, которому необходимо предоставить/изменить/прекратить доступ;
- перечень компонентов ИСПДн, с указанием полномочий в рамках этих систем (например, 1С-Зарплата и управление персоналом чтение, 1С-Бухгалтерия чтение, запись, удаление);
- цели и основание для оформления доступа;
- дополнительные сведения при необходимости.


=== Контроль физического доступа к компонентам ИСПДн

Мероприятия по физическому контролю доступа включают:

- контроль доступа на территорию;
- контроль доступа в помещения с оборудованием ИСПДн;
- контроль доступа к техническим средствам ИС;
- контроль перемещений физических компонентов ИСПДн.

=== Работа с носителями ПДн

Порядок работы с носителями персональных данных определен в документе "Положение о порядке хранения и уничтожения носителей персональных данных".


=== Резервирование ПДн

Резервное копирование ПДн необходимо осуществлять для информационных систем персональных данных, для которых, согласно частной модели угроз, актуально обеспечение целостности и доступности ПДн. Резервное копирование осуществляется с целью восстановления ПДн, уничтоженных или модифицированных в следствии несанкционированного доступа к ним.

Резервное копирование должно производится на магнитные ленты, либо на другие носители информации с необходимым уровнем надежности и долговечности.

Не допускается хранение резервных копий в месте основного хранилища информации. Хранение резервных копий долнж осуществляться в сейфах (металлических шкафах).

Ответственным за резервирование необходимых массивов ПДн является работник, ответственный за обеспечение безопасности ПДн.

=== Обнаружение фактов НСД к ПДн

Перечень мероприятий, направленных на предотвращение неправомерного использования персональных данных Работниками, включает в себя:

- выявление совершенных в процессе выполнения служебных обязанностей действий, нарушающих требования при работе с персональными данными;
- признание этих действий (бездействия) в установленном порядке неправомерными, предотвращение и возмещение вреда;
- привлечение виновных к ответственности.

К организационным и правовым мерам выявления и предотвращения неправомерных действий с персональными данными относятся:

- ознакомление всех Работников под подпись с настоящим Положением и иными документами ЗАО КБ «ЛАДА-КРЕДИТ», устанавливающими порядок обработки персональных данных Работников, а также об их правах и обязанностях в этой области;
- регулярное доведение до сведения Работников информации о возможных нарушениях при обработке персональных данных, ответственности при их совершении;
- регулярный контроль выполнения внутренних нормативных документов осуществляет Департамент безопасности и Отдел Внутреннего Контроля;
- внесение в договорные отношения требований действующего законодательства в области персональных данных;
- служебное расследование фактов неправомерного обращения с персональными данными.

К техническим мерам обеспечения безопасности персональных данных относятся:

- обеспечение защиты от несанкционированного доступа к персональным данным;
- обеспечение нейтрализации актуальных угроз безопасности при обработке персональных данных;
- ведение автоматизированного журнала учета предоставления доступа к персональным данным в автоматизированных системах или передаче персональных данных в другие системы (между системами и подсистемами), а также печать на бумажные носители и копирование информации на сменные носители информации;
- ведение журнала учета посетителей, принимаемых на территории ЗАО КБ «ЛАДА-КРЕДИТ» (Приложение 16 к настоящему Положению).

Организацию и контроль за законностью обработки персональных данных осуществляет Лицо ответственное за организацию обработки персональных данных.


=== Контроль за принимаемыми мерами по обеспечению безопасности персональных данных

План внутренних проверок состояния защиты персональных данных в ЗАО КБ «ЛАДА-КРЕДИТ»

В целях контроля соответствия процессов обработки ПДн законодательству РФ в области обработки и защиты ПДн, требованиям к защите персональных данных, локальным актам ЗАО КБ "ЛАДА-КРЕДИТ" проводятся внутренние контрольные мероприятия.

Состав внутренних контрольных мероприятий определяется Комиссией. Типовой перечень контрольных мероприятий в отдельных подсистемах СЗПДн приведен в Таблице 1. Кроме того, в ходе контрольных мероприятий обязательно производятся выборочные проверки работников на предмет знания и соблюдения ими требований локальных актов Компании в сфере ПДн.

Контрольк применяемых мер по обеспечению безопасности ПДн осуществляется работником, ответственным за обеспечение безопасности ПДн.

.Таблица №1 План внутренних проверок состояния защиты персональных данных в ЗАО КБ «ЛАДА-КРЕДИТ»

[options="header" cols="2,100,50,100"]
|=================================================================
|№	|Наименование проверки	|Периодичность выполнения	|Ответственные за выполнение
|1	|Плановый пересмотр частных моделей угроз безопасности	|Не реже одного раза в два года	|Лицо ответственное за обеспечение безопасности персональных данных
|2	|Проверка достаточности имеющихся нормативных документов, регламентирующих обеспечение безопасности ПДн	|Не реже одного раза в год	|Лицо ответственное за обеспечение безопасности персональных данных
|3	|Проверка качества знаний Работников в вопросах обеспечения безопасности ПДн	|Два раза в год	|Лицо ответственное за обеспечение безопасности персональных данных
|4	|Контроль за использованием Средств Защиты Информации	|Два раза в год	|Лицо ответственное за обеспечение безопасности персональных данных
|5	|Контроль за обеспечением безопасности персональных данных, при их обработке без использования средств автоматизации	|Два раза в год	|Лицо ответственное за обеспечение безопасности персональных данных
|6	|Контроль за обеспечением безопасности персональных данных, при их обработке в информационных системах персональных данных	|Два раза в год	|Лицо ответственное за обеспечение безопасности персональных данных
|7	|Проверка списка лиц, допущенных к обработке персональных данных	|Ежеквартально	|Лицо ответственное за организацию обработки персональных данных
|8	|Контроль за соответствием действующему законодательству текста типовых форм Договоров, содержащих персональные данные, в процессе их разработки и согласования.	|Постоянно, в текущем режиме	|Юридическое управление
|=================================================================
