= Положение о защите персональных данных
:toc:
:toc-title: Содержание

:sectlink:



:numbered:
== Термины, определения и используемые сокращения

В настоящем Положении используются следующие термины и определения:

Персональные данные:: 
	любая информация, относящаяся к прямо или косвенно определенному или определяемому физическому лицу (субъекту персональных данных).
Обработка персональных данных:: 
	любое действие (операция) или совокупность действий (операций), совершаемых с использованием средств автоматизации или без использования таких средств с персональными данными, включая сбор, запись, систематизацию, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передачу (распространение, предоставление, доступ), обезличивание, блокирование, удаление, уничтожение персональных данных.
Оператор персональных данных::
	государственный орган, муниципальный орган, юридическое или физическое лицо, самостоятельно или совместно с другими лицами организующие и (или) осуществляющие обработку персональных данных, а также определяющие цели обработки персональных данных, состав персональных данных, подлежащих обработке, действия (операции), совершаемые с персональными данными.
Распространение персональных данных::
	действия, направленные на раскрытие персональных данных определенному лицу или определенному кругу лиц.
Блокирование персональных данных::
	временное прекращение обработки персональных данных (за исключением случаев, если обработка необходима для уточнения персональных данных).
Уничтожение персональных данных::
	действия, в результате которых становится невозможным восстановить содержание персональных данных в информационной системе персональных данных и (или) в результате которых уничтожаются материальные носители персональных данных.
Обезличивание персональных данных:: 
	действия, в результате которых становится невозможным без использования дополнительной информации определить принадлежность персональных данных конкретному субъекту персональных данных.
Информационная система персональных данных (ИСПДн)- совокупность содержащихся в базах данных персональных данных и обеспечивающих их обработку информационных технологий и технических средств.
Конфиденциальность персональных данных::
	обязательное для соблюдения оператором или иным получившим доступ к персональным данным лицом требование не допускать их распространения или предоставления третьим лицам без согласия субъекта персональных данных или требования Федерального закона.
Трансграничная передача персональных данных::
	передача персональных данных на территорию иностранного государства органу власти иностранного государства, иностранному физическому лицу или иностранному юридическому лицу.
Персональные данные, сделанные общедоступными субъектом персональных данных::
	персональные данные, доступ неограниченного круга лиц к которым предоставлен с согласия субъекта персональных данных либо по его просьбе.
Контролируемая зона::
	пространство (территория, здание, часть здания, помещение), в котором исключено неконтролируемое пребывание лиц, не имеющих постоянного или разового допуска, и посторонних транспортных средств.
Несанкционированный доступ (несанкционированные действия)::
	доступ к информации или действия с информацией, осуществляемые с нарушением установленных прав и (или) правил доступа к информации или действий с ней с применением штатных средств информационной системы или средств, аналогичных им по функциональным и техническим характеристикам.
Работодатель::
	ЗАО КБ «ЛАДА-КРЕДИТ», вступивший в трудовые отношения с Работником и правовые отношения с соискателем на вакантную должность.
Работник::
	физическое лицо, вступившее в трудовые отношения с ЗАО КБ «ЛАДА-КРЕДИТ».
Соискатель::
	физическое лицо, вступившее в правовые отношения с ЗАО КБ «ЛАДА-КРЕДИТ» с целью устройства на работу в ЗАО КБ «ЛАДА-КРЕДИТ».


== Назначение и область действия документа

Положение об обеспечении безопасности персональных данных (далее -Положение) предназначено для организации работ по защите персональных данных от неправомерного или случайного доступа к ним, уничтожения, изменения, блокирования, копирования, предоставления, распространения персональных данных, а также от иных неправомерных действий в отношении персональных данных при их обработке в <Наименование организации> (далее - Организация)

Требования настоящего Положения распространяются на структурные подразделения Организации и должностных лиц, принимающих участие в обеспечении безопасности ПДн, в т. ч. на Комиссию по обеспечению безопасности персональных данных (далее – Комиссия).

Настоящее Положения не распространяется на обеспечение безопасности сведений ограниченного доступа (в т. ч. конфиденциальной информации), не содержащих ПДн.

Требования настоящего Положения должны быть доведены до всех лиц, участвующих в обеспечении безопасности ПДн в Организации, под подпись.

== Мероприятия в рамках обеспечения безопасности ПДн

Настоящее Положение разработано в соответствии с Конституцией РФ, Трудовым кодексом РФ, Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных», Федеральным законом от 27.07.2006 № 149-ФЗ «Об информатизации, информационных технологиях и о защите информации», Постановлениями Правительства РФ от 01.11.2012 № 1119 «Об утверждении требований к защите персональных данных при их обработке в информационных системах персональных данных» и от 15.09.2008 № 687 «Об утверждении Положения об особенностях обработки персональных данных, осуществляемой без использования средств автоматизации», Распоряжением Правительства РФ от 21.03.1994 № 358-р «Об обеспечении сохранности документов по личному составу» и иными нормативными актами, действующими на территории Российской Федерации
	
Мероприятия в рамках обеспечения безопасности ПДн осуществляются в рамках проведения следующих работ:
	
	* Определение правил доступа к персональным данным;
	* Контроль физического доступа к компонентам информационных систем персональных данных;
	* Организация работы с носителями ПДн;
	* Определение порядка резервирования персональных данных;
	* Обнаружение фактов несанкционированного доступа к персональным данным и принятием мер;
	* Контроль за обеспечением необходимого уровня защищенности ПДн.

=== Правила доступа к персональным данным

==== Предоставление прав доступа

Работники ЗАО КБ «ЛАДА-КРЕДИТ» выполняют действия по обработке персональных данных в соответствии со служебной необходимостью и возложенными на Работников функциями.

Доступ к персональным данным предоставляется в соответствии с документом "Список лиц, допущенных к обработке персональных данных" (далее - Список). Список разрабатывается работником, ответственным за организацию обработки ПДн, согласуется с работником, ответственным за обеспечение безопасности ПДн и утверждается Председателем правления ЗАО КБ "ЛАДА-КРЕДИТ".

Основанием для предоставления прав доступа к ПДн являются:
- прием нового работника в штат ЗАО КБ "ЛАДА-КРЕДИТ" на должность, подразумевающую обработку ПДн работником для выполнения своих служебных обязанностей;
- перевод работника на должность, подразумевающую обработку ПДн работником.

Для предоставления доступа, руководитель структурного подразделения, к которому относится работник, направляет работнику, ответсвенному за обеспечение безопасности ПДн заявку на предоставление доступа в соответствии с разделом <<Оформление заявок на доступ к ПДн>> 

По завершении предоставления доступа работнику, ответственный за безопасность ПДн уведомляет об этом руководителя, оформившего Заявку, электронным письмом или по телефону (срок исполнения Заявки не превышает *3* рабочих дней).

==== Изменение или прекращение прав доступа

Основанием для пересмотра или прекращения прав доступа являются:

- увольнение работинка;
- перевод работника на другую должность, если новая должность подразумевает изменение или прекращение прав доступа к ПДн;
- проведение в отношении работника служебного расследования, если в рамках расследования работнику ограничивается доступ к ПДн.

Для изменения или прекращениея прав доступа, руководитель структурного подразделения, к которому относится работник, направляет работнику, ответсвенному за обеспечение безопасности ПДн заявку в соответствии с разделом <<Оформление заявок на доступ к ПДн>> 

По завершении предоставления доступа работнику, ответственный за безопасность ПДн уведомляет об этом руководителя, оформившего Заявку, электронным письмом или по телефону (срок исполнения Заявки не превышает *3* рабочих дней).


==== Оформление заявок на доступ к ПДн

В данном разделе изложен порадок оформления заявок на предоставление, изменение или прекращение прав доступа к ПДн (далее – Заявка) 
Оформление Заявки осуществляется одним из следующих способов:

- заявка в бумажном виде;
- электронная заявка.

Заявка подается ответственному за обеспечение безопасности ПДн от имени Руководителя структурного подразделения, в котором числится работник. Заявка содержит следующие сведения:

- Ф.И.О. и должность руководителя структурного подразделения, подающего Заявку;
- Ф.И.О. и должность работника, которому необходимо предоставить/изменить/прекратить доступ;
- перечень компонентов ИСПДн, с указанием полномочий в рамках этих систем (например, 1С-Зарплата и управление персоналом чтение, 1С-Бухгалтерия чтение, запись, удаление);
- цели и основание для оформления доступа;
- дополнительные сведения при необходимости.


=== Контроль физического доступа к компонентам ИСПДн

Мероприятия по физическому контролю доступа включают:

- контроль доступа на территорию;
- контроль доступа в помещения с оборудованием ИСПДн;
- контроль доступа к техническим средствам ИС;
- контроль перемещений физических компонентов ИСПДн.

=== Работа с носителями ПДн

описать работу с носителями ПДн

=== Резервирование ПДн

описать работы по резервированию ПДн

=== Обнаружение фактов НСД к ПДн

Описать работы по реагированию на инциденты

=== Контроль за принимаемыми мерами по обеспечению безопасности персональных данных

описать работы по контролю за мерами по обеспечению безопасности ПДн
