== Термины, определения и используемые сокращения

== Назначение и область действия документа

Положение об обеспечении безопасности персональных данных (далее -Положение) предназначено для организации работ по защите персональных данных от неправомерного или случайного доступа к ним, уничтожения, изменения, блокирования, копирования, предоставления, распространения персональных данных, а также от иных неправомерных действий в отношении персональных данных при их обработке в <Наименование организации> (далее - Организация)

Требования настоящего Положения распространяются на структурные подразделения Организации и должностных лиц, принимающих участие в обеспечении безопасности ПДн, в т. ч. на Комиссию по обеспечению безопасности персональных данных (далее – Комиссия).

Настоящее Положения не распространяется на обеспечение безопасности сведений ограниченного доступа (в т. ч. конфиденциальной информации), не содержащих ПДн.

Требования настоящего Положения должны быть доведены до всех лиц, участвующих в обеспечении безопасности ПДн в Организации, под подпись.

== Мероприятия в рамках обеспечения безопасности ПДн

	Настоящее Положение разработано в соответствии с Конституцией РФ, Трудовым кодексом РФ, Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных», Федеральным законом от 27.07.2006 № 149-ФЗ «Об информатизации, информационных технологиях и о защите информации», Постановлениями Правительства РФ от 01.11.2012 № 1119 «Об утверждении требований к защите персональных данных при их обработке в информационных системах персональных данных» и от 15.09.2008 № 687 «Об утверждении Положения об особенностях обработки персональных данных, осуществляемой без использования средств автоматизации», Распоряжением Правительства РФ от 21.03.1994 № 358-р «Об обеспечении сохранности документов по личному составу» и иными нормативными актами, действующими на территории Российской Федерации
	
	Мероприятия в рамках обеспечения безопасности ПДн осуществляются в рамках проведения следующих работ:
	
	* Определение правил доступа к персональным данным;
	* Контроль физического доступа к компонентам информационных систем персональных данных;
	* Организация работы с носителями ПДн;
	* Определение порядка резервирования персональных данных;
	* Обнаружение фактов несанкционированного доступа к персональным данным и принятием мер;
	* Контроль за обеспечением необходимого уровня защищенности ПДн.

=== Правила доступа к персональным данным

=== Контроль физического доступа к компонентам ИСПДн

Мероприятия по физическому контролю доступа включают:

* контроль доступа на территорию;
* контроль доступа в помещения с оборудованием ИСПДн;
* контроль доступа к техническим средствам ИС;
* контроль перемещений физических компонентов ИСПДн.

=== Работа с носителями ПДн

=== Резервирование ПДн

=== Обнаружение фактов НСД к ПДн

== Контроль за принимаемыми мерами по обеспечению безопасности персональных данных
